	[300454] = {
		unidentifiedDisplayName = "Glacier Flower Meow Power(Vital)",
		unidentifiedResourceName = "Glacier_F_Orb_161",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Glacier Flower Meow Power(Vital)",
		identifiedResourceName = "Glacier_F_Orb_161",
		identifiedDescriptionName = {
			"MaxHP +2500",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"MaxHP +5%",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"MaxHP +5%",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"MaxHP +5%"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[300455] = {
		unidentifiedDisplayName = "Copo Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Copo Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Damage against monsters of ^FF0000Small^000000 size by 15%.",
			"_______________________",
			"^0000FFFor each 4 Refine Levels^000000:",
			"Increases Damage against monsters of ^FF0000Small^000000 size by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Damage against monsters of ^FF0000Medium^000000 size by 12%.",
			" ",
			"^0000FFFor each 3 Refine Levels^000000:",
			"Increases Damage against monsters of ^FF0000Medium^000000 size by additional 4%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300456] = {
		unidentifiedDisplayName = "Icewind's Egg Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Icewind's Egg Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Decreases After Skill Delay by 3%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Decreases After Skill Delay by additional 2%.",
			"_______________________",
			"When ^990099Armor Level^000000 of compounded equipment is ^0000FF2^000000:",
			"Decreases Variable Casting Time by 5%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Headgear",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300457] = {
		unidentifiedDisplayName = "Gray Icewind Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Gray Icewind Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"ATK +5%",
			"_______________________",
			"Decreases Variable Casting Time by 5%.",
			"Increases SP Consumption by 7%.",
			"_______________________",
			"When ^990099Armor Level^000000 of compounded equipment is ^0000FF2^000000:",
			"POW +3, CON +3",
			"Decreases Variable Casting Time by additional 3%.",
			"_______________________",
			"When equipped with ^990099Copo Card^000000:",
			"Increases Physical Damage against monsters of ^FF0000Large^000000 size by 10%.",
			" ",
			"^0000FFFor each 2 Refine Levels^000000:",
			"Increases Physical Damage against monsters of ^FF0000Large^000000 size by additional 3%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Shoes",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300458] = {
		unidentifiedDisplayName = "Icewind Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Icewind Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"MATK +5%",
			"_______________________",
			"Decreases Variable Casting Time by 5%.",
			"Increases SP Consumption by 7%.",
			"_______________________",
			"When ^990099Armor Level^000000 of compounded equipment is ^0000FF2^000000:",
			"SPL +3, CON +3",
			"Decreases Variable Casting Time by additional 3%.",
			"_______________________",
			"When equipped with ^990099Copo Card^000000:",
			"Increases Magical Damage against monsters of ^FF0000Large^000000 size by 10%.",
			" ",
			"^0000FFFor each 2 Refine Levels^000000:",
			"Increases Magical Damage against monsters of ^FF0000Large^000000 size by additional 3%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Shoes",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300459] = {
		unidentifiedDisplayName = "Jormungandr Church Bishop Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Jormungandr Church Bishop Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"P.ATK +2, S.MATK +2",
			"_______________________",
			"Decreases Variable Casting Time by 3%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Headgear",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300460] = {
		unidentifiedDisplayName = "Jormungandr Guardian Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Jormungandr Guardian Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"MATK +40",
			"_______________________",
			"Increases Magical Damage with ^777777Neutral^000000, ^777777Shadow^000000 and ^777777Ghost^000000 element by 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Magical Damage with ^777777Neutral^000000, ^777777Shadow^000000 and ^777777Ghost^000000 element by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Magical Damage with ^777777Neutral^000000, ^777777Shadow^000000 and ^777777Ghost^000000 element by additional 10%.",
			"_______________________",
			"When equipped with ^990099Jormungandr Church Bishop Card^000000:",
			"Increases Magical Damage with ^777777Neutral^000000, ^777777Shadow^000000 and ^777777Ghost^000000 element by additional 15%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300461] = {
		unidentifiedDisplayName = "Suspicious Iwin Soldier Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Suspicious Iwin Soldier Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"ATK +40",
			"_______________________",
			"Increases Melee Physical Damage by 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Melee Physical Damage by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Melee Physical Damage by additional 10%.",
			"_______________________",
			"When equipped with ^990099Jormungandr Church Bishop Card^000000:",
			"Increases Melee Physical Damage by additional 15%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300462] = {
		unidentifiedDisplayName = "Superior Rgan Shaman Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Superior Rgan Shaman Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"MATK +40",
			"_______________________",
			"Increases Magical Damage with ^FF0000Fire^000000, ^33CC00Wind^000000 and ^CC5500Earth^000000 element by 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Magical Damage with ^FF0000Fire^000000, ^33CC00Wind^000000 and ^CC5500Earth^000000 element by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Magical Damage with ^FF0000Fire^000000, ^33CC00Wind^000000 and ^CC5500Earth^000000 element by additional 10%.",
			"_______________________",
			"When equipped with ^990099Jormungandr Church Bishop Card^000000:",
			"Increases Magical Damage with ^FF0000Fire^000000, ^33CC00Wind^000000 and ^CC5500Earth^000000 element by additional 15%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300463] = {
		unidentifiedDisplayName = "Superior Rgan Healer Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Superior Rgan Healer Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"MATK +40",
			"_______________________",
			"Increases Magical Damage with ^0000BBWater^000000, ^663399Poison^000000 and ^777777Holy^000000 element by 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Magical Damage with ^0000BBWater^000000, ^663399Poison^000000 and ^777777Holy^000000 element by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Magical Damage with ^0000BBWater^000000, ^663399Poison^000000 and ^777777Holy^000000 element by additional 10%.",
			"_______________________",
			"When equipped with ^990099Jormungandr Church Bishop Card^000000:",
			"Increases Magical Damage with ^0000BBWater^000000, ^663399Poison^000000 and ^777777Holy^000000 element by additional 15%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300464] = {
		unidentifiedDisplayName = "Jormungandr Church Shaman Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Jormungandr Church Shaman Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Magical Damage with ^0000BBWater^000000, ^663399Poison^000000 and ^777777Holy^000000 element by 25%.",
			"_______________________",
			"Base ^CC6600INT^000000 at least ^FF000090^000000:",
			"Increases SP Consumption by 7%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Right)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300465] = {
		unidentifiedDisplayName = "Jormungandr Sanctuary Guardian Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Jormungandr Sanctuary Guardian Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"STR +10, VIT +15, LUK -25",
			"_______________________",
			"Decreases damage taken from monsters of every size by 20%.",
			"Decreases Magical Damage against monsters of ^777777Holy^000000, ^777777Shadow^000000, ^777777Ghost^000000 and ^663399Poison^000000 element by 25%.",
			"_______________________",
			"^0000FFFor each Refine Level^000000:",
			"DEF +20, RES +5",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Physical Damage against monsters of ^0000BBWater^000000, ^33CC00Wind^000000, ^CC5500Earth^000000 and ^FF0000Fire^000000 element by 25%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Melee and Ranged Physical Damage by 10%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Shield",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300466] = {
		unidentifiedDisplayName = "Jormungandr Sanctuary Cleaner Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Jormungandr Sanctuary Cleaner Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"ATK +40",
			"_______________________",
			"Increases Ranged Physical Damage by 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Ranged Physical Damage by additional 5%.",
			"_______________________",
			"When ^990099Weapon Level^000000 of compounded equipment is ^0000FF5^000000:",
			"Increases Ranged Physical Damage by additional 10%.",
			"_______________________",
			"When equipped with ^990099Jormungandr Church Bishop Card^000000:",
			"Increases Ranged Physical Damage by additional 15%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300467] = {
		unidentifiedDisplayName = "Angel Slug Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Angel Slug Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Melee Physical Damage by 15%.",
			"_______________________",
			"Base ^CC6600LUK^000000 at least ^FF000090^000000:",
			"Critical -15",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Right)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300468] = {
		unidentifiedDisplayName = "Snow Rabbit Slug Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Snow Rabbit Slug Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Ranged Physical Damage by 15%.",
			"_______________________",
			"Base ^CC6600LUK^000000 at least ^FF000090^000000:",
			"Critical -15",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Right)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300469] = {
		unidentifiedDisplayName = "Melibe Slug Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Melibe Slug Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Magical Damage with ^FF0000Fire^000000, ^33CC00Wind^000000 and ^CC5500Earth^000000 element by 25%.",
			"_______________________",
			"Base ^CC6600INT^000000 at least ^FF000090^000000:",
			"Increases SP Consumption by 7%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Right)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300470] = {
		unidentifiedDisplayName = "Bear Bug Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Bear Bug Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Magical Damage with ^777777Neutral^000000, ^777777Shadow^000000 and ^777777Ghost^000000 element by 25%.",
			"_______________________",
			"Base ^CC6600INT^000000 at least ^FF000090^000000:",
			"Increases SP Consumption by 7%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Right)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300471] = {
		unidentifiedDisplayName = "Fallen Angel Slug Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Fallen Angel Slug Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"MaxHP -20%",
			"_______________________",
			"Increases Physical Damage against monsters of ^FF0000Demon^000000 and ^FF0000Brute^000000 race by 25%.",
			"Increases Physical Damage against monsters of ^777777Shadow^000000 and ^0000BBWater^000000 element by 25%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Accessory(Left)",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300472] = {
		unidentifiedDisplayName = "Ultimate Rasgandr Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Ultimate Rasgandr Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Magical Damage against monsters of ^FF0000Boss^000000 class by 40%.",
			"MaxHP -15%",
			"_______________________",
			"^0000FFRefine Level +12^000000:",
			"S.MATK +15",
			"_______________________",
			"^CC6600Base Level^000000 at least ^FF0000200^000000:",
			"SPL +15",
			"_______________________",
			"Base ^CC6600SPL^000000 at least ^FF000090^000000:",
			"MATK +15%",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Armor",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300473] = {
		unidentifiedDisplayName = "Snowstorm Angel Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Snowstorm Angel Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Ranged Physical Damage by 30%.",
			"_______________________",
			"For each ^0000FF20^000000 base ^CC6600LUK^000000:",
			"Critical -5",
			"_______________________",
			"^0000FFFor each 3 Refine Levels^000000:",
			"Increases Ranged Physical Damage by additional 5%.",
			"_______________________",
			"When ^990099Armor Level^000000 of compounded equipment is ^0000FF2^000000:",
			"Increases Physical damage against monsters of ^FF0000Boss^000000 class by 10%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Garment",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300474] = {
		unidentifiedDisplayName = "Sanctuary Cleaning Chief Card",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Sanctuary Cleaning Chief Card",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"Increases Melee Physical Damage by 30%.",
			"_______________________",
			"For each ^0000FF20^000000 base ^CC6600LUK^000000:",
			"Critical -5",
			"_______________________",
			"^0000FFFor each 3 Refine Levels^000000:",
			"Increases Melee Physical Damage by additional 5%.",
			"_______________________",
			"When ^990099Armor Level^000000 of compounded equipment is ^0000FF2^000000:",
			"Increases Physical damage against monsters of ^FF0000Boss^000000 class by 10%.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Garment",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[450264] = {
		unidentifiedDisplayName = "Unidentified Armor",
		unidentifiedResourceName = "코튼셔츠",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Armor",
		identifiedResourceName = "Glacier_Armor",
		identifiedDescriptionName = {
			"Armor forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"ATK +120",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"ATK +15, DEF +15",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Physical Damage by 5%.",
			"Increases Attack Speed (decreases After Attack Delay by 10%).",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"P.ATK +3",
			"Increases Attack Speed (decreases After Attack Delay by additional 5%).",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"DEF +100",
			"Decreases After Skill Delay by 5%.",
			"_______________________",
			"When equipped with ^990099Glacier Manteau^000000:",
			"ATK +50",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: POW +3, CON +3, After Skill Delay -5%.",
			"[Grade C]: ATK +3%, P.ATK +2.",
			"_______________________",
			"^0000CCType:^000000 Armor",
			"^0000CCDefense:^000000 168",
			"^0000CCWeight:^000000 240",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450265] = {
		unidentifiedDisplayName = "Unidentified Armor",
		unidentifiedResourceName = "코튼셔츠",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Robe",
		identifiedResourceName = "Glacier_Robe",
		identifiedDescriptionName = {
			"A robe forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"MATK +120",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"MATK +15, DEF +15",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Magical Damage with every element by 5%.",
			"Decreases Variable Casting Time by 10%.",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"S.MATK +3",
			"Decreases Variable Casting Time by additional 5%.",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"DEF +100",
			"Decreases After Skill Delay by 5%.",
			"_______________________",
			"When equipped with ^990099Glacier Muffler^000000:",
			"MATK +50",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: SPL +3, CON +3, After Skill Delay -5%.",
			"[Grade C]: MATK +3%, S.MATK +2.",
			"_______________________",
			"^0000CCType:^000000 Armor",
			"^0000CCDefense:^000000 120",
			"^0000CCWeight:^000000 120",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450266] = {
		unidentifiedDisplayName = "Unidentified Garment",
		unidentifiedResourceName = "후드",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Manteau",
		identifiedResourceName = "Glacier_Manteau",
		identifiedDescriptionName = {
			"A manteau forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"MaxHP +2500, MaxSP +500",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"MaxHP +200, MaxSP +50",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Attack Speed (decreases After Attack Delay by 7%).",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"POW +3",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Decreases Variable Casting Time by 5%.",
			"_______________________",
			"When equipped with ^990099Glacier Boots^000000:",
			"Increases Physical Damage by 15%.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: ATK +3%, P.ATK +2.",
			"[Grade C]: Variable Casting Time -10%.",
			"_______________________",
			"^0000CCType:^000000 Garment",
			"^0000CCDefense:^000000 112",
			"^0000CCWeight:^000000 160",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450267] = {
		unidentifiedDisplayName = "Unidentified Garment",
		unidentifiedResourceName = "후드",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Muffler",
		identifiedResourceName = "Glacier_Muffler",
		identifiedDescriptionName = {
			"A muffler forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"MaxHP +2000, MaxSP +1000",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"MaxHP +150, MaxSP +100",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Decreases Variable Casting Time by 7%.",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"SPL +3",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"Increases Attack Speed (decreases After Attack Delay by 5%).",
			"_______________________",
			"When equipped with ^990099Glacier Shoes^000000:",
			"Increases Magical Damage with every element by 15%.",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: MATK +3%, S.MATK +2.",
			"[Grade C]: After Attack Delay -10%.",
			"_______________________",
			"^0000CCType:^000000 Garment",
			"^0000CCDefense:^000000 80",
			"^0000CCWeight:^000000 80",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[450268] = {
		unidentifiedDisplayName = "Unidentified Shoes",
		unidentifiedResourceName = "슈즈",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Shoes",
		identifiedResourceName = "Glacier_Shoes",
		identifiedDescriptionName = {
			"Shoes forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"MaxHP +6%, MaxSP +6%",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"MaxSP +1%, DEF +15",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Magical Damage with every element by 7%.",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"S.MATK +3",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"DEF +100",
			"Decreases Variable Casting Time by 7%.",
			"_______________________",
			"When equipped with ^990099Glacier Robe^000000:",
			"MATK +7%",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: RES +25, MRES +25.",
			"[Grade C]: S.MATK +2, SPL +2, CON +2.",
			"_______________________",
			"^0000CCType:^000000 Shoes",
			"^0000CCDefense:^000000 70",
			"^0000CCWeight:^000000 100",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[470196] = {
		unidentifiedDisplayName = "Unidentified Shoes",
		unidentifiedResourceName = "슈즈",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Glacier Boots",
		identifiedResourceName = "Glacier_Boots",
		identifiedDescriptionName = {
			"Boots forged by imbuing the power of a Divine Cat Whiskers with Issgard's Glacier.",
			"You can add abilities by granting a legend with special magical powers.",
			"_______________________",
			"MaxHP +8%, MaxSP +4%",
			"_______________________",
			"^0000FFFor each 2 Refine Levels^000000:",
			"MaxSP +1%, DEF +15",
			"_______________________",
			"^0000FFRefine Level +7^000000:",
			"Increases Physical Damage by 7%.",
			"_______________________",
			"^0000FFRefine Level +9^000000:",
			"P.ATK +3",
			"_______________________",
			"^0000FFRefine Level +10^000000:",
			"DEF +100",
			"Increases Attack Speed (decreases After Attack Delay by 7%).",
			"_______________________",
			"When equipped with ^990099Glacier Armor^000000:",
			"ATK +7%",
			"_______________________",
			"^CC3D3D[Bonus by Grade]^000000",
			"[Grade D]: RES +25, MRES +25.",
			"[Grade C]: P.ATK +2, POW +2, CON +2.",
			"_______________________",
			"^0000CCType:^000000 Shoes",
			"^0000CCDefense:^000000 98",
			"^0000CCWeight:^000000 200",
			"^0000CCArmor Level:^000000 2",
			"_______________________",
			"^0000CCRequirement:^000000",
			"Base Level 230"
		},
		slotCount = 1,
		ClassNum = 0,
		costume = false
	},
	[1001217] = {
		unidentifiedDisplayName = "Divine Cat Whiskers",
		unidentifiedResourceName = "Ep20_Cat_Whiskers",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Divine Cat Whiskers",
		identifiedResourceName = "Ep20_Cat_Whiskers",
		identifiedDescriptionName = {
			"The whiskers of a White Cat, a mysterious creature of Issgard. It feels like Jormungandr's magic has been condensed. It is considered a symbol of good luck in the ice castle and its population.",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001218] = {
		unidentifiedDisplayName = "Power Recovery Device",
		unidentifiedResourceName = "Ep20_Jor_Device",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Power Recovery Device",
		identifiedResourceName = "Ep20_Jor_Device",
		identifiedDescriptionName = {
			"A device to absorb the remaining magic power in the land of Issgard.",
			"_______________________",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001226] = {
		unidentifiedDisplayName = "Rgan's Advanced Magic Core",
		unidentifiedResourceName = "Ep20_Rgan_Core_F",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Rgan's Advanced Magic Core",
		identifiedResourceName = "Ep20_Rgan_Core_F",
		identifiedDescriptionName = {
			"A magic core obtained by defeating Rgan's. The crystallization of the mana absorbed from Jormungandr. This magic core contains magic of considerable quality.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001227] = {
		unidentifiedDisplayName = "Coral Bracelet",
		unidentifiedResourceName = "Ep20_Coral_Bangle",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Coral Bracelet",
		identifiedResourceName = "Ep20_Coral_Bangle",
		identifiedDescriptionName = {
			"A bracelet crafted from corals.",
			"It seems that the smooth surface has subtle magic power.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001228] = {
		unidentifiedDisplayName = "Seashell Hairpin",
		unidentifiedResourceName = "Ep20_Shell_Hairpin",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Seashell Hairpin",
		identifiedResourceName = "Ep20_Shell_Hairpin",
		identifiedDescriptionName = {
			"A hairpin decorated with seashells.",
			"You can't equip it yourself, but collectibles dealers like it.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001229] = {
		unidentifiedDisplayName = "Seaweed Belt",
		unidentifiedResourceName = "Ep20_Seaweed_Belt",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Seaweed Belt",
		identifiedResourceName = "Ep20_Seaweed_Belt",
		identifiedDescriptionName = {
			"A belt made of cloth woven from seaweed.",
			"The subtle scent of the sea rises.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001230] = {
		unidentifiedDisplayName = "Scale Armor Fragment",
		unidentifiedResourceName = "Ep20_Cataphract_Piece",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Scale Armor Fragment",
		identifiedResourceName = "Ep20_Cataphract_Piece",
		identifiedDescriptionName = {
			"A piece of armor made of scales.",
			"It is made of fairly hard scales.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001231] = {
		unidentifiedDisplayName = "Soft Fluorescent Cells(Sour)",
		unidentifiedResourceName = "Ep20_Fluor_Cell_Sour",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Soft Fluorescent Cells(Sour)",
		identifiedResourceName = "Ep20_Fluor_Cell_Sour",
		identifiedDescriptionName = {
			"A soft cell of a mollusk that lives in the sea.",
			"It is said to glow brightly at night.",
			"If you take a bite, you can feel the sour taste that pops out, but I don't think so.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001232] = {
		unidentifiedDisplayName = "Soft Fluorescent Cells(Salty)",
		unidentifiedResourceName = "Ep20_Fluor_Cell_Salty",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Soft Fluorescent Cells(Salty)",
		identifiedResourceName = "Ep20_Fluor_Cell_Salty",
		identifiedDescriptionName = {
			"A soft cell of a mollusk that lives in the sea.",
			"It is said to glow blue at night.",
			"If you take a bite, you can feel the salty taste, but I don't think so.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001233] = {
		unidentifiedDisplayName = "Soft Fluorescent Cells(Sweet)",
		unidentifiedResourceName = "Ep20_Fluor_Cell_Sweet",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Soft Fluorescent Cells(Sweet)",
		identifiedResourceName = "Ep20_Fluor_Cell_Sweet",
		identifiedDescriptionName = {
			"A soft cell of a mollusk that lives in the sea.",
			"It is said to glow yellow at night.",
			"If you take a bite, you will feel the sweet taste, but I don't think so.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001234] = {
		unidentifiedDisplayName = "Bear Skin",
		unidentifiedResourceName = "Ep20_Ice_Bearskin",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Bear Skin",
		identifiedResourceName = "Ep20_Ice_Bearskin",
		identifiedDescriptionName = {
			"Bear skin.",
			"It is said to be very tough and is used to make leather armor.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001235] = {
		unidentifiedDisplayName = "Monster's Tooth",
		unidentifiedResourceName = "Ep20_Unknown_Canine",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Monster's Tooth",
		identifiedResourceName = "Ep20_Unknown_Canine",
		identifiedDescriptionName = {
			"The sharp fangs of a strange creature.",
			"It has a considerable rarity and is popular with collectibles dealers.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001236] = {
		unidentifiedDisplayName = "Sparkling Snowflakes",
		unidentifiedResourceName = "Ep20_Twinkling_Snow",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Sparkling Snowflakes",
		identifiedResourceName = "Ep20_Twinkling_Snow",
		identifiedDescriptionName = {
			"Snowflakes that sparkle with a special ingredient.",
			"It's shiny appearance makes it popular among collectors.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001237] = {
		unidentifiedDisplayName = "Angel's Tail",
		unidentifiedResourceName = "Ep20_Angels_Tail",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Angel's Tail",
		identifiedResourceName = "Ep20_Angels_Tail",
		identifiedDescriptionName = {
			"The tail of a mollusk that lives in Issgard.",
			"The muscles are very well developed.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001238] = {
		unidentifiedDisplayName = "Mysterious Magic Mass",
		unidentifiedResourceName = "Ep20_Mystic_Spl_Colt",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Mysterious Magic Mass",
		identifiedResourceName = "Ep20_Mystic_Spl_Colt",
		identifiedDescriptionName = {
			"An irregular mass of pure and mysterious magic power.",
			"If you do it wrong, it seems that big things will happen.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001239] = {
		unidentifiedDisplayName = "Broken Trident",
		unidentifiedResourceName = "Ep20_Broken_Trident",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Broken Trident",
		identifiedResourceName = "Ep20_Broken_Trident",
		identifiedDescriptionName = {
			"An Iwin's broken trident.",
			"Recycling doesn't seem possible.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001240] = {
		unidentifiedDisplayName = "Iwin Private Hat",
		unidentifiedResourceName = "Ep20_Iwin_Private_C",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Iwin Private Hat",
		identifiedResourceName = "Ep20_Iwin_Private_C",
		identifiedDescriptionName = {
			"A yellow glove-shaped hat that symbolizes Private Irwin.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001241] = {
		unidentifiedDisplayName = "Private Iwin Hat",
		unidentifiedResourceName = "Ep20_Iwin_Priva_Co_C",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Private Iwin Hat",
		identifiedResourceName = "Ep20_Iwin_Priva_Co_C",
		identifiedDescriptionName = {
			"A blue glove-shaped hat that symbolizes Private Iwin.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001242] = {
		unidentifiedDisplayName = "Corporal Iwin Hat",
		unidentifiedResourceName = "Ep20_Iwin_Corporal_C",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Corporal Iwin Hat",
		identifiedResourceName = "Ep20_Iwin_Corporal_C",
		identifiedDescriptionName = {
			"A green glove-shaped hat that symbolizes Corporal Iwin.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001243] = {
		unidentifiedDisplayName = "Iwin's Sergeant Hat",
		unidentifiedResourceName = "Ep20_Iwin_Sergeant_C",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Iwin's Sergeant Hat",
		identifiedResourceName = "Ep20_Iwin_Sergeant_C",
		identifiedDescriptionName = {
			"A red glove-shaped hat that symbolizes Iwin's Sergeant.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001244] = {
		unidentifiedDisplayName = "Large Gray Feather",
		unidentifiedResourceName = "Ep20_Huge_Feather_G",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Large Gray Feather",
		identifiedResourceName = "Ep20_Huge_Feather_G",
		identifiedDescriptionName = {
			"The gray feathers of a large bird.",
			"Can be sold to a collectibles dealer.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001245] = {
		unidentifiedDisplayName = "Large White Feather",
		unidentifiedResourceName = "Ep20_Huge_Feather_W",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Large White Feather",
		identifiedResourceName = "Ep20_Huge_Feather_W",
		identifiedDescriptionName = {
			"The white feathers of a large bird.",
			"Can be sold to a collectibles dealer.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001246] = {
		unidentifiedDisplayName = "Copo's Feathers",
		unidentifiedResourceName = "Ep20_Copo_Head_F",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Copo's Feathers",
		identifiedResourceName = "Ep20_Copo_Head_F",
		identifiedDescriptionName = {
			"White hair feathers sprouted from the top of Copo's head.",
			"Can be sold to a collectibles dealer.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001247] = {
		unidentifiedDisplayName = "Copo's Eggshell Fragment",
		unidentifiedResourceName = "Ep20_Copo_Egg_Shell",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Copo's Eggshell Fragment",
		identifiedResourceName = "Ep20_Copo_Egg_Shell",
		identifiedDescriptionName = {
			"A piece of Copo's eggshell.",
			"It doesn't seem to have any use.",
			"_______________________",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001248] = {
		unidentifiedDisplayName = "Source Stone of Pure Magic",
		unidentifiedResourceName = "EP20_D_P_Ore",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Source Stone of Pure Magic",
		identifiedResourceName = "EP20_D_P_Ore",
		identifiedDescriptionName = {
			"A source stone with pure magical power.",
			"A different level of magic than Issgard's normal magic flowed out.",
			"^0000CCWeight:^000000 3"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1869
	},
	[1001249] = {
		unidentifiedDisplayName = "Crystal of Pure Magic",
		unidentifiedResourceName = "EP20_D_P_Crystal",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Crystal of Pure Magic",
		identifiedResourceName = "EP20_D_P_Crystal",
		identifiedDescriptionName = {
			"A crystal made of condensed Source Stones with high purity and pure magical power.",
			"It is sealed so that it is not affected by other magical powers around it.",
			"^0000CCWeight:^000000 5"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1870
	},
	[1001250] = {
		unidentifiedDisplayName = "Pure Magic Extract",
		unidentifiedResourceName = "EP20_D_P_Extract",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Pure Magic Extract",
		identifiedResourceName = "EP20_D_P_Extract",
		identifiedDescriptionName = {
			"A bottle containing magical ingredients extracted from crystals of pure magical power.",
			"_______________________",
			"Where to use:",
			"<NAVI>[Beep Beep Ring]<INFO>icas_in,170,65,0,100,0,0</INFO></NAVI>",
			"_______________________",
			"^0000CCWeight:^000000 3"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1871
	},
	[1001251] = {
		unidentifiedDisplayName = "Snake God's Scales",
		unidentifiedResourceName = "EP20_D_Scale",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Snake God's Scales",
		identifiedResourceName = "EP20_D_Scale",
		identifiedDescriptionName = {
			"A piece of scale that fell from the snake god's body.",
			"Although it is a small piece of scale, it possesses tremendous magical power.",
			"_______________________",
			"^0000CCWeight:^000000 5"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1190
	},
	[1001254] = {
		unidentifiedDisplayName = "Corrupted Heart Fragment of Ymir",
		unidentifiedResourceName = "Ep20_Ymir_Heart",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Corrupted Heart Fragment of Ymir",
		identifiedResourceName = "Ep20_Ymir_Heart",
		identifiedDescriptionName = {
			"A piece of Ymir's heart that Bagot used his own power. At the end, it was used in Rasgand's demi-myth experiment, and it is imbued with turbid energy.",
			"_______________________",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001153] = {
		unidentifiedDisplayName = "Ancient Icewind Egg",
		unidentifiedResourceName = "Ep20_Ice_Egg",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Ancient Icewind Egg",
		identifiedResourceName = "Ep20_Ice_Egg",
		identifiedDescriptionName = {
			"An Ancient Icewind egg that fell out of the nest.",
			"Put them in a safe place so they can hatch safely.",
			"_______________________",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	[1001154] = {
		unidentifiedDisplayName = "Snakeberry",
		unidentifiedResourceName = "Ep20_Jor_Berry",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Snakeberry",
		identifiedResourceName = "Ep20_Jor_Berry",
		identifiedDescriptionName = {
			"A red colored crystal stone found in small amounts throughout Issgard.",
			"Rgans like it very much.",
			"_______________________",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
	